### ISSUE TITLE
how to solve verificatin failed error?

### ISSUE THREAD

**Issue by mohammadooman** [LBank-exchange/lbank-connector-python#2]
when i use api for  require authentication actions i get verification failed

```
if __name__ == '__main__':
    api_key ='*******************************'
    api_secret ='*********************************'
    base_url = "https://api.lbkex.com/"
    sign_method = "HmacSHA256"
    client=BlockHttpClient(sign_method,api_key,api_secret,base_url)
    payload = {}
    response = client.http_request("post", "/v2/supplement/user_info_account.do", payload=payload)
    print(response)

{'result': 'false', 'msg': 'Verification failed', 'error_code': 10002, 'ts': 1725359007130}
```
is there any way to find the reason or help me to solve this?

**Comment by akftes** [comment]
i have same problem .... in use CCXT library i get  `99336.605 Array ( ) test
Fatal error: Uncaught ccxt\PermissionDenied: Invalid authorization in /home/robatixi/domains/robatix.ir/public_html/vendor/ccxt/ccxt/php/lbank.php:2995 Stack trace: #0 /home/robatixi/domains/robatix.ir/public_html/vendor/ccxt/ccxt/php/Exchange.php(1610): ccxt\lbank->handle_errors() #1 /home/robatixi/domains/robatix.ir/public_html/vendor/ccxt/ccxt/php/Exchange.php(5168): ccxt\Exchange->fetch() #2 /home/robatixi/domains/robatix.ir/public_html/vendor/ccxt/ccxt/php/Exchange.php(5188): ccxt\Exchange->fetch2() #3 /home/robatixi/domains/robatix.ir/public_html/vendor/ccxt/ccxt/php/abstract/lbank.php(317): ccxt\Exchange->request() #4 /home/robatixi/domains/robatix.ir/public_html/vendor/ccxt/ccxt/php/lbank.php(1500): ccxt\abstract\lbank->spotPrivatePostSupplementCreateOrder() #5 /home/robatixi/domains/robatix.ir/public_html/samplecallapi.php(63): ccxt\lbank->create_order() #6 {main} thrown in /home/robatixi/domains/robatix.ir/public_html/vendor/ccxt/ccxt/php/lbank.php on line 2995`   
error..... :(

**Comment by mehranml** [comment]
same error here

**Comment by ghost** [comment]
same problem - how to solve?
{'result': 'false', 'msg': 'Parameters such as api_key and sign can not be null', 'error_code': 10201, 'ts': 1746459074621}

**Comment by GoldRat** [comment]
I have the same issue running your API example:

![Image](https://github.com/user-attachments/assets/596cdc93-8a8a-4ec7-b9e5-dddd2a9a58f9)

api_key and sign are definitely not null.

**Comment by KingAmid** [comment]
No funds
